Question 1:
--
__Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays__

In [36]:
import numpy as np

array1=[]
for i in range(4):
    y=[]
    for j in range(4):
        y.append(int(input("Enter array1 elements:")))
    array1.append(y)
array1=np.array(array1)
array2=[]
for i in range(4):
    z=[]
    for j in range(4):
        z.append(int(input("Enter array2 elements:")))
    array2.append(z)
array2=np.array(array2)

print(array1)
print(array2)
print("Comparision greater:",np.greater(array1,array2))
print("Comparision greater_equal:",np.greater_equal(array1,array2))
print("Comparision less:",np.less(array1,array2))
print("Comparision less_equal:",np.less_equal(array1,array2))

Enter array1 elements:1
Enter array1 elements:2
Enter array1 elements:3
Enter array1 elements:4
Enter array1 elements:5
Enter array1 elements:6
Enter array1 elements:7
Enter array1 elements:8
Enter array1 elements:9
Enter array1 elements:10
Enter array1 elements:11
Enter array1 elements:12
Enter array1 elements:13
Enter array1 elements:14
Enter array1 elements:15
Enter array1 elements:16
Enter array2 elements:12
Enter array2 elements:32
Enter array2 elements:1
Enter array2 elements:2
Enter array2 elements:4
Enter array2 elements:6
Enter array2 elements:54
Enter array2 elements:89
Enter array2 elements:34
Enter array2 elements:12
Enter array2 elements:23
Enter array2 elements:32
Enter array2 elements:122
Enter array2 elements:43
Enter array2 elements:43
Enter array2 elements:53
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 12  32   1   2]
 [  4   6  54  89]
 [ 34  12  23  32]
 [122  43  43  53]]
Comparision greater: [[False False  True  True]
 [ True False False False]

Question 2:
--
__Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives__

In [43]:
import numpy as np
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)
print(np.full([10],5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5 5 5 5 5 5 5 5 5 5]


Question 3:
--
__Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array__

In [45]:
import numpy as np

array1=[]
for i in range(2):
    y=[]
    for j in range(2):
        y.append(int(input("Enter array1 elements:")))
    array1.append(y)
array1=np.array(array1)
print(array1)
print("Sum of array elements=",np.sum(array1))
print("Sum of elements in a column",np.sum(array1, axis=0))
print("Sum of elements in a row",np.sum(array1, axis=1))

Enter array1 elements:1
Enter array1 elements:2
Enter array1 elements:3
Enter array1 elements:4
[[1 2]
 [3 4]]
Sum of array elements= 10
Sum of elements in a column [4 6]
Sum of elements in a row [3 7]


Question 4:
--
__Write a NumPy program to add, subtract, multiply, divide arguments element-wise.__

In [46]:
import numpy as np

array1=[]
for i in range(2):
    y=[]
    for j in range(2):
        y.append(int(input("Enter array1 elements:")))
    array1.append(y)
array1=np.array(array1)
array2=[]
for i in range(2):
    z=[]
    for j in range(2):
        z.append(int(input("Enter array2 elements:")))
    array2.append(z)
array2=np.array(array2)

print(array1)
print(array2)
print("Adding array elements:",np.add(array1,array2))
print("Subtracting array elements:",np.subtract(array1,array2))
print("Multiplying array elements:",np.multiply(array1,array2))
print("Dividing array elements:",np.divide(array1,array2))

Enter array1 elements:1
Enter array1 elements:2
Enter array1 elements:3
Enter array1 elements:4
Enter array2 elements:5
Enter array2 elements:6
Enter array2 elements:7
Enter array2 elements:8
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Adding array elements: [[ 6  8]
 [10 12]]
Subtracting array elements: [[-4 -4]
 [-4 -4]]
Multiplying array elements: [[ 5 12]
 [21 32]]
Dividing array elements: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Question 5:
--
__Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.__

In [48]:
import numpy as np

array1=[]
for i in range(2):
    y=[]
    for j in range(2):
        y.append(int(input("Enter array1 elements:")))
    array1.append(y)
array1=np.array(array1)
print(array1)
print("Sine=",np.sin(np.array(array1)* np.pi / 180.))
print("Cosine=",np.cos(np.array(array1)* np.pi / 180.))
print("Tangent=",np.tan(np.array(array1)* np.pi / 180.))

Enter array1 elements:0
Enter array1 elements:30
Enter array1 elements:45
Enter array1 elements:24
[[ 0 30]
 [45 24]]
Sine= [[0.         0.5       ]
 [0.70710678 0.40673664]]
Cosine= [[1.         0.8660254 ]
 [0.70710678 0.91354546]]
Tangent= [[0.         0.57735027]
 [1.         0.44522869]]


Question 6:
--
__Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels__

In [50]:
import pandas as pd
import numpy as np

class_data={"Name":['abc','def','ghi','jkl'],"Roll_Number":[1,2,3,4],"Branch":['ECE','CSE','IT','EEE'],"Year":[4,4,4,4]}
labels=['i','ii','iii','iv']
df=pd.DataFrame(class_data,index=labels)
print(df)

    Name  Roll_Number Branch  Year
i    abc            1    ECE     4
ii   def            2    CSE     4
iii  ghi            3     IT     4
iv   jkl            4    EEE     4


Question 7:
--
__Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.__

In [53]:
import pandas as pd
import numpy as np

class_data={"Name":['abc','def','ghi','jkl'],"Roll_Number":[1,2,3,4],"Branch":['ECE','CSE','IT','EEE'],"Year":[4,4,4,4]}
labels=['i','ii','iii','iv']
df=pd.DataFrame(class_data,index=labels)
print(df)
print(df[['Name','Roll_Number']])

    Name  Roll_Number Branch  Year
i    abc            1    ECE     4
ii   def            2    CSE     4
iii  ghi            3     IT     4
iv   jkl            4    EEE     4
    Name  Roll_Number
i    abc            1
ii   def            2
iii  ghi            3
iv   jkl            4


Question 8:
--
__Write a Pandas program to join the two given dataframes along rows and assign all data.__

In [63]:
import pandas as pd
import numpy as np

class1_data=pd.DataFrame({"Name":['abc','def','ghi','jkl'],"Roll_Number":[1,2,3,4],"Branch":['ECE','CSE','IT','EEE'],"Year":[4,4,4,4]})
class2_data=pd.DataFrame({"Name":['pqr','stu','vwx','yz'],"Roll_Number":[5,6,7,8],"Branch":['Mech','Civil','AE','EIE'],"Year":[3,4,1,2]})
print(class1_data)
print(class2_data)
print(pd.concat([class1_data, class2_data]))

  Name  Roll_Number Branch  Year
0  abc            1    ECE     4
1  def            2    CSE     4
2  ghi            3     IT     4
3  jkl            4    EEE     4
  Name  Roll_Number Branch  Year
0  pqr            5   Mech     3
1  stu            6  Civil     4
2  vwx            7     AE     1
3   yz            8    EIE     2
  Name  Roll_Number Branch  Year
0  abc            1    ECE     4
1  def            2    CSE     4
2  ghi            3     IT     4
3  jkl            4    EEE     4
0  pqr            5   Mech     3
1  stu            6  Civil     4
2  vwx            7     AE     1
3   yz            8    EIE     2


Question 9:
--
__Write a Pandas program to detect missing values of a given DataFrame. Display True or False.__

In [75]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df =pd.DataFrame({"Name":['abc','def','ghi',np.NaN],"Roll_Number":[1,2,3,None],"Branch":['ECE','CSE','IT','EEE'],"Year":[4,4,4,None]})
print(df)
print("\nMissing values of given dataframe:")
print(df.isna())

  Name  Roll_Number Branch  Year
0  abc          1.0    ECE   4.0
1  def          2.0    CSE   4.0
2  ghi          3.0     IT   4.0
3  NaN          NaN    EEE   NaN

Missing values of given dataframe:
    Name  Roll_Number  Branch   Year
0  False        False   False  False
1  False        False   False  False
2  False        False   False  False
3   True         True   False   True


Question 10:
--
__Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.__

In [77]:
import pandas as pd
print(pd.Series(['abc','def','ghi','jkl']))

0    abc
1    def
2    ghi
3    jkl
dtype: object
